name: simple_todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1-dev.2

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1
  pinput: ^4.0.0
  riverpod_annotation: ^2.3.3
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true

assets:
  - assets/www/
